version: '3'
services:
  myapp:
    build: .
    volumes:
      - ./config:/app/config
      - ./logs:/app/logs
      - ./output:/app/output
      - /Users/jimmy/Data/OneDrive - Latinia Interactive Business, S.A/Jimmy/brrMac/SCL:/app/data
      - ./app:/app/source