[LOGGING]
# Ruta al archivo de log principal, donde se registran eventos generales de la aplicación.
LogFilePath=./logs/log_qosmetrics_process.log
# Ruta al archivo de log para el procesamiento de archivos, útil para depurar la lectura y ordenamiento de archivos.
LogFilePathFiles = ./logs/log_read.log
# Nivel de detalle de los logs. Opciones: DEBUG, INFO, WARNING, ERROR, CRITICAL.
LogLevel = DEBUG

[PROCESS_FILES]
# Ruta al directorio donde se encuentran los archivos de log a procesar.
InputPath=./data/testJuanC01Sept/
# Patrón para filtrar los archivos a procesar dentro del directorio InputPath.
# Utiliza sintaxis de comodines (ej: *.log, Limsp*.log).
FilePattern=only.log
# Número de particiones en las que se dividirán las transacciones incompletas para su procesamiento.
# A mayor número de particiones, menor el tamaño de cada archivo de partición.
num_partitions = 7
# Tamaño máximo del "chunk" de datos que se mantiene en memoria antes de escribir a disco.
# Se usa para controlar el uso de memoria del programa.
Chunk_size = 1000000
# Lista de valores válidos para el campo "action" en los registros de log.
# Se utiliza para filtrar los registros a procesar.
valid_actions = MNEWTRANS,NEWTRANS,SEND
# Lista de valores válidos para el campo "subcomponent" en los registros de log.
# Se utiliza para filtrar los registros a procesar.
valid_subcomponents = FailOverManager
# Nombre base para los archivos binarios donde se guardan las transacciones incompletas,
# seguido de un número de partición.
IncompleteTransactionsFile = ./output/binary_file
# Patrones para ordenar los archivos de log antes de procesarlos.
# Se utiliza para asegurar que los logs se procesen en el orden correcto.
# Los patrones se evalúan en orden, y los archivos que coinciden con un patrón anterior tienen mayor prioridad.
file_order_patterns = *47*,*48*,limsp_adaptor*,limmsp_bus_massive*,limsp_bus*,limsp_collector*
# Nombre del archivo CSV donde se guardan los resultados finales del procesamiento.
ResultFinalFile = ./output/desdoblamiento0109_1.csv
# Intervalo de tiempo (en segundos) en el que se registran logs de progreso.
timeToLog = 10

# Expresión regular utilizada para analizar cada línea de los archivos de log.
# Define los campos que se extraerán de cada línea.
#log_pattern = \[(?P<timestamp>\d{4}/\d{2}/\d{2} \d{2}:\d{2}:\d{2}(?:\.\d{3})?)\]\s+(?P<action>.+?)\s+(?P<subcomponent>.+?)\s+(?P<details>.+)
