[LOGGING]
LogFilePath=./logs/log_qosmetrics_process.log
LogFilePathFiles = ./logs/log_read.log
LogFilePathReadBinary = ./logs/log_readBinary.log
LogFilePathIncomplete = ./logs/log_processIncomplete.log

LogLevel = INFO

[PROCESS_FILES]
InputPath=./data/Aval/
FilePattern=Limsp*.log
num_partitions = 15
Chunk_size = 1000000
#mem_trx_security = 1000000 
#writeDiscarded = False
# Lista de valores válidos para action
valid_actions = MNEWTRANS,NEWTRANS,SEND
# Lista de valores válidos para subcomponent
valid_subcomponents = FailOverManager
IncompleteTransactionsFile = ./output/binary_file
file_order_patterns = *47*,*48*,limsp_adaptor*,limmsp_bus_massive*,limsp_bus*,limsp_collector*
#file_order_patterns = Limsp_1*,Limsp_2*, Limsp_3*,Limsp_4*,Limsp_5*
CompletedTransactionsFile = ./output/result_duration_aval.dat
ResultFinalFile = ./output/aval_dateinColKO_jpq33.csv
timeToLog = 10

# Patrón para procesar líneas de log
#log_pattern = \[(?P<timestamp>\\d{4}/\\d{2}/\\d{2} \\d{2}:\\d{2}:\\d{2}(?:\\.\\d{3})?)\\]\\s+(?P<action>.+?)\\s+(?P<subcomponent>.+?)\\s+(?P<details>.+)