[DURATION]
#Directorio dónde escribirá el log principal del script
LogFilePath=./logs/GENERAL/19122024/log_duration_GENERAL.log
#Directorio del log que registra la cantidad de transacciones que encuentra en cada archivo
LogWriteFilePath=./logs/GENERAL/19122024/log_write_GENERAL.log
#Directorio del log que cuenta la velocidad de lecutra de cada archivo
LogReadFilePath=./logs/GENERAL/19122024/log_read_GENERAL.log
#Ubicación de los archivos que consumirá (logs del cliente)
#InputPath=/mnt/LogsOTC/BANORTE/309_LATSUP-3766_Recoleccion Log analisis transaccional 30 abril 2024/2024-05-06 01 L01/ACT_depurados_29
InputPath=/mnt/LogsOTC/GENERAL/248_LATSUP-4760_Recoleccion logs analisis transaccional 13 y 14 de Diciembre/2024-12-16 01 L01/SDP
#InputPath=./data
FilePattern=*act*.log
#Archivo dónde se almacenaran las transacciones descartadas
LogDiscardedTrx =./logs/GENERAL/19122024/log_discardTrx_GENERAL.log
#Define si se escribiran las transacciones que se descartan True False. por defecto False
writeDiscarded = false
#FilePattern=limsp_bus_act_11.log
#Ubicación del archivo resultante de la ejecución
#OutputFilePath=/mnt/LogsOTC/BANORTE/309_LATSUP-3766_Recoleccion Log analisis transaccional 30 abril 2024/2024-05-06 01 L01/QoS_Metrics/duration/result_duration_no_sorted_Banorte_30_04_2024_v5_2.csv
OutputFilePath=/mnt/LogsOTC/GENERAL/248_LATSUP-4760_Recoleccion logs analisis transaccional 13 y 14 de Diciembre/2024-12-16 01 L01/SDP/QoS_Metrics/duration/result_duration_no_sorted_GENERAL_19122024.csv
#OutputFilePath= ./output/resultKO.csv
Chunk_size_write = 600000
#establece cada cuantos archivos de logs procesados escribe las transacciones al archivo definitivo
Chunk_size_write_files = 70
# Lista de valores válidos para action
valid_actions = MNEWTRANS,NEWTRANS,SEND
# Lista de valores válidos para subcomponent
valid_subcomponents = FailOverManager,ServiceCenterOu
#limite seguridad para mantener transacciones en memoria, por defecto 7 Millones
window_sizing = 5000000

[CONSOLIDATE]

InputDirectory=/mnt/LogsOTC/GENERAL/248_LATSUP-4760_Recoleccion logs analisis transaccional 13 y 14 de Diciembre/2024-12-16 01 L01/SDP/QoS_Metrics/duration
#Patrón de búsqueda de archivo del duration dentro del directorio InputDirector
#FilePattern = result_duration_no_sorted_*.csv
FilePattern = result_duration_sorted_GENERAL_19122024.csv
#Directorio dónde ubicará los logs
LogDirectory = ./logs/GENERAL/19122024/
#Nombre del log
logName = log_consolidate_GENERAL_19122024.log
#Ubicación del archivo resultante
#OutputResult = /mnt/LogsOTC/BANORTE/265_LATSUP-3186_Recolección Logs peak Transaccional Octubre 2023/2023-10-19 01 L01/SDP_depurados_DR/Outputs/Consolidate/29-DIC/v1-result_29122023_consolidate_Mnew.csv
OutputResult =/mnt/LogsOTC/GENERAL/248_LATSUP-4760_Recoleccion logs analisis transaccional 13 y 14 de Diciembre/2024-12-16 01 L01/SDP/QoS_Metrics/consolidate/result_consolidate_GENERAL_19122024.csv
OutputInots =/mnt/LogsOTC/GENERAL/248_LATSUP-4760_Recoleccion logs analisis transaccional 13 y 14 de Diciembre/2024-12-16 01 L01/SDP/QoS_Metrics/consolidate/result_consolidate_inot_GENERAL_19122024.csv
#Intervalo para escribir transacciones en los logs
LogInterval = 1000000
#bloque de procesamiento del archivo
Chunk_size_write = 10000000


[TRANSACTION_PROCESSOR]
# Archivo de entrada
#InputFile=/mnt/LogsOTC/BCI/172_LATSUP-3711_Análisis transaccional abril 2024/2024-05-17 01 l01/QoS_Metrics/consolidate/result_consolidate_BCI_22_05_2024.csv
#InputFile=/QoS_Metrics/c4.csv
InputFile=/mnt/LogsOTC/GENERAL/248_LATSUP-4760_Recoleccion logs analisis transaccional 13 y 14 de Diciembre/2024-12-16 01 L01/SDP/QoS_Metrics/consolidate/result_consolidate_GENERAL_19122024.csv
# Archivo de salida
#OutputFile=/mnt/LogsOTC/BCI/172_LATSUP-3711_Análisis transaccional abril 2024/2024-05-17 01 l01/QoS_Metrics/consolidate/result_transactionp_BCI_22_05_2024.csv
OutputFile=/mnt/LogsOTC/GENERAL/248_LATSUP-4760_Recoleccion logs analisis transaccional 13 y 14 de Diciembre/2024-12-16 01 L01/SDP/QoS_Metrics/consolidate/result_transactionp_GENERAL_19122024.csv
# Tamaño del bloqueonsolidate/result_consolidate_BOLIVARIANO_05_06_202
# Tamaño del bloque
BlockSize=1000000
# Directorio del log principal del script
LogFilePath=./logs/GENERAL/19122024/log_transaction_processor_GENERAL.log
# Directorio del log que registra la cantidad de transacciones que encuentra en cada archivo
LogWriteFilePath=./logs/GENERAL/19122024/log_write_transaction_processor_GENERAL_19122024.log


#####Nuevas secciones de configuración#####

[LOGGING]
LogFilePath=./logs/log_qosmetrics_process.log
LogFilePathFiles = ./logs/log_read.log
LogFilePathReadBinary = ./logs/log_readBinary.log
LogFilePathIncomplete = ./logs/log_processIncomplete.log
LogLevel = DEBUG

[PROCESS_FILES]
InputPath=/mnt/LogsOTC/BANORTE/358_LATSUP-4666_Recoleccion Log analisis transaccional 29 noviembre/2024-12-04 01 L01/ACT
FilePattern=*act*.log
#establece el límite que tendra el diccionario para acumular líneas de los archivos de logs y será un porcentaje para los registros incompletos en memoria "slide slicing"
Chunk_size = 7000000
#mem_trx_security = 1000000

writeDiscarded = False
# Lista de valores válidos para action
valid_actions = MNEWTRANS,NEWTRANS,SEND
# Lista de valores válidos para subcomponent
valid_subcomponents = FailOverManager,ServiceCenterOu
tmpdatabinary = /mnt/LogsOTC/BANORTE/358_LATSUP-4666_Recoleccion Log analisis transaccional 29 noviembre/2024-12-04 01 L01/ACT/data_tmp_bnt
file_order_patterns = limsp_adaptor*,limmsp_bus_massive*,limsp_bus*,limsp_collector*

CompletedTransactionsFile = /mnt/LogsOTC/BANORTE/358_LATSUP-4666_Recoleccion Log analisis transaccional 29 noviembre/2024-12-04 01 L01/ACT/CompletedTransactionsFile_4feb.dat

#archivo temporal creado dentro de "BinaryTransactionReader" para terminar de cerrar transacciones entre las incompletas que aún hayan quedado y las completas generadas por "ReviewIncomplete"
ReviewTransactionsFile = ./output/completeall_review_4feb.dat 
ResultFinalFile = ./output/final_transactions_bnt_4feb.csv
#estas son las nuevas incompletas después del proceso de revisión de incompletas. Generado por "ReviewIncomplete". Debe ser la entrada para "BinaryTransctionReader"
IncompleteReviewTransactionsFile = /mnt/LogsOTC/BANORTE/358_LATSUP-4666_Recoleccion Log analisis transaccional 29 noviembre/2024-12-04 01 L01/ACT/IncompleteReviewTransactionsFile_4feb.dat 
timeToLog = 300
