[DURATION]
#Ubicación de los archivos que consumirá (logs del cliente)
InputPath=/mnt/NAS/SCHCL/335_LATSUP-4369_Análisis transaccional SCHCL Producción - Septiembre 2024/2024-10-02 01 L01
#Directorio y nombre del archivo del logs perteneciente al script, en este registro,
LogFilePath=./logs/log_duration.log
#Expone la cantidad de registros que encuentra en cada archivo, y que a su vez, registra en el archivo final
LogWriteFilePath=./logs/log_write_duration.log
#Expone la cantidad de archivos leidos 
LogReadFilePath=./logs/log_read_duration.log
FilePattern=*act*.log
#Archivo dónde se almacenaran las transacciones descartadas
LogDiscardedTrx =./logs/log_discardTrx.log
#Define si se escribiran las transacciones que se descartan True False. por defecto False
writeDiscarded = False
#FilePattern=limsp_bus_act_11.log
#Ubicación del archivo resultante de la ejecución
OutputFilePath=/mnt/NAS/SCHCL/335_LATSUP-4369_Análisis transaccional SCHCL Producción - Septiembre 2024/2024-10-02 01 L01/duration/result_duration_18102024.csv
Chunk_size_write = 1000000
#establece cada cuantos archivos de logs procesados escribe las transacciones al archivo definitivo
Chunk_size_write_files = 70
# Lista de valores válidos para action
valid_actions = MNEWTRANS,NEWTRANS,SEND
# Lista de valores válidos para subcomponent
valid_subcomponents = FailOverManager,ServiceCenterOu
#limite seguridad para mantener transacciones en memoria, por defecto 7 Millones
#window_sizing = 3000000

[CONSOLIDATE]
#directorio dónde estarán el archivo duration a procesar
#InputDirectory = ./output
InputDirectory=/mnt/NAS/SCHCL/335_LATSUP-4369_Análisis transaccional SCHCL Producción - Septiembre 2024/2024-10-02 01 L01/duration/
#Patrón de búsqueda de archivo del duration dentro del directorio InputDirector
FilePattern = result_duration_sorted.csv
#Directorio dónde ubicará los logs
LogDirectory = ./logs
#Nombre del log
logName = log_consolidate_07102024.log
#Ubicación del archivo resultante
OutputResult= /mnt/NAS/SCHCL/335_LATSUP-4369_Análisis transaccional SCHCL Producción - Septiembre 2024/2024-10-02 01 L01/consolidate/output_consolidate.csv
OutputInots = /mnt/NAS/SCHCL/335_LATSUP-4369_Análisis transaccional SCHCL Producción - Septiembre 2024/2024-10-02 01 L01/consolidate/result_consolidate_Inot.csv
#Intervalo para escribir transacciones en los logs
LogInterval = 1000000
#bloque de procesamiento del archivo
Chunk_size_write = 10000000

[TRANSACTION_PROCESSOR]
# Archivo de entrada
#InputFile=/mnt/NAS/BCI/172_LATSUP-3711_Análisis transaccional abril 2024/2024-05-17 01 l01/QoS_Metrics/consolidate/result_consolidate_BCI_22_05_2024.csv
InputFile= /mnt/NAS/INTERBANK/264_LATSUP-4181_Recoleccion Log analisis transaccional 31 Julio 2024/2024-08-20 01 L01/ACT_ok/QoS_Metrics/consolidate/result_consolidate_INTERBANK_22082024.csv
# Archivo de salida
#OutputFile=/mnt/NAS/BCI/172_LATSUP-3711_Análisis transaccional abril 2024/2024-05-17 01 l01/QoS_Metrics/consolidate/result_transactionp_BCI_22_05_2024.csv
OutputFile= /mnt/NAS/INTERBANK/264_LATSUP-4181_Recoleccion Log analisis transaccional 31 Julio 2024/2024-08-20 01 L01/ACT_ok/QoS_Metrics/consolidate/result_transactionp_INTERBANK_22082024.csv
# Tamaño del bloque
# Tamaño del bloque
BlockSize=1000000
# Directorio del log principal del script
LogFilePath=./logs/log_transaction_procesor_INTERBANK_22082024.log
# Directorio del log que registra la cantidad de transacciones que encuentra en cada archivo
LogWriteFilePath=./logs/log_write_transaction_processor_INTERBANK_22082024.log

[PROCESS]
# Lista de valores válidos para action
valid_actions = MNEWTRANS,NEWTRANS,SEND
# Lista de valores válidos para subcomponent
valid_subcomponents = FailOverManager,ServiceCenterOu
#archivo de log del proceso de lectura de logs y escritura a la BD
LogFilePathReadLogs=./logs/log_database_processlogs.log
#archivo de log del proceso de lectura de bd y escritura a archivo final
LogFilePath=./logs/log_database.log
LogWriteFilePath = ./logs/log_write_process.log
chunk_commit_databse = 5000000
#tamaño del bloque a leer de la base de datos
size_process = 1000000
#Ubicación de los archivos que consumirá (logs del cliente)
InputPath=/mnt/NAS/SCHCL/335_LATSUP-4369_Análisis transaccional SCHCL Producción - Septiembre 2024/2024-10-02 01 L01
FilePattern=*act*.log
Chunk_size_write = 100
OutputFilePath =  ./output/result_processDB_1551.csv
progress_percentage = 10

[DATABASELITE]
Path = qos_metrics.db
TableSchemaFile = ./config/transactions_schema.sql
chunk_insert = 10

[WRITE_RESULT]
# Tamaño del lote a leer de la base de datos en cada iteración
size_process = 50000
# Tamaño del lote a escribir en el archivo CSV
Chunk_size_write = 100000 
# Ruta del archivo CSV de salida       
OutputFilePath = ./output/result_processqos_lite.csv 
writeDiscarded = False 


#####Nuevas secciones de configuración#####

[LOGGING]
LogFilePath=./logs/log_qosmetrics_process.log
LogFilePathFiles = ./logs/log_read.log
LogFilePathReadBinary = ./logs/log_readBinary.log
LogFilePathIncomplete = ./logs/log_processIncomplete.log
LogLevel = DEBUG

[PROCESS_FILES]
InputPath=/mnt/NAS/BANORTE/358_LATSUP-4666_Recoleccion Log analisis transaccional 29 noviembre/2024-12-04 01 L01/ACT
FilePattern=*act*.log
#Ubicación del archivo resultante de la ejecución
OutputFilePath=./output/resultDx.csv
#establece el límite que tendra el diccionario para acumular líneas de los archivos de logs y será un porcentaje para los registros incompletos en memoria "slide slicing"
Chunk_size = 7000000

writeDiscarded = False
# Lista de valores válidos para action
valid_actions = MNEWTRANS,NEWTRANS,SEND
# Lista de valores válidos para subcomponent
valid_subcomponents = FailOverManager,ServiceCenterOu
IncompleteTransactionsFile = /mnt/NAS/BANORTE/358_LATSUP-4666_Recoleccion Log analisis transaccional 29 noviembre/2024-12-04 01 L01/ACT/IncompleteTransactionsFile_23dic.dat
CompletedTransactionsFile = /mnt/NAS/BANORTE/358_LATSUP-4666_Recoleccion Log analisis transaccional 29 noviembre/2024-12-04 01 L01/ACT/CompletedTransactionsFile_23dic.dat

#archivo temporal creado dentro de "BinaryTransactionReader" para terminar de cerrar transacciones entre las incompletas que aún hayan quedado y las completas generadas por "ReviewIncomplete"
ReviewTransactionsFile = ./output/completeall_review_23dic.dat 
ResultFinalFile = ./output/final_transactions_bnt_23_dic.csv
#estas son las nuevas incompletas después del proceso de revisión de incompletas. Generado por "ReviewIncomplete". Debe ser la entrada para "BinaryTransctionReader"
IncompleteReviewTransactionsFile = /mnt/NAS/BANORTE/358_LATSUP-4666_Recoleccion Log analisis transaccional 29 noviembre/2024-12-04 01 L01/ACT/IncompleteReviewTransactionsFile_2dic.dat 
timeToLog = 120