[LOGGING]
LogFilePath=./logs/log_qosmetrics_process.log
LogFilePathFiles = ./logs/log_read.log
LogFilePathReadBinary = ./logs/log_readBinary.log
LogFilePathIncomplete = ./logs/log_processIncomplete.log
LogLevel = DEBUG

[PROCESS_FILES]
InputPath=/mnt/LogsOTC/Cliente_B/006_QoS_muestra/20250317/
FilePattern=*act*.log
#establece el límite que tendra el diccionario para acumular líneas de los archivos de logs y será un porcentaje para los registros incompletos en memoria "slide slicing"
Chunk_size = 3000000
#El valor por defecto del numero de particiones es 30
#num_partitions = 10

# Lista de valores válidos para action
valid_actions = MNEWTRANS,NEWTRANS,SEND
# Lista de valores válidos para subcomponent
valid_subcomponents = FailOverManager,ServiceCenterOu
IncompleteTransactionsFile = /mnt/LogsOTC/Cliente_B/006_QoS_muestra/20250317/data_bin_clientB
#IncompleteTransactionsFile = /mnt/LogsOTC/SCHCL/347_LATSUP-5100_Flujo Transaccional Marzo 2025/2025-03-17 03 L01/SDP/binary_file
#orden en que se procesaran los logs. Se deja para el final lo que no se encuentre en estos patrones
file_order_patterns = limsp_adaptor*,limsp_jms_adaptor*,limmsp_bus_massive*,limsp_bus*,Limsp_act*,limsp_collector*
ResultFinalFile = /mnt/LogsOTC/Cliente_B/006_QoS_muestra/20250317/result_clienteB_19032025.csv
#tiempo en segundos que se escriben logs de progreso
timeToLog = 60
# Patrón para procesar líneas de log
#log_pattern = \[(?P<timestamp>\\d{4}/\\d{2}/\\d{2} \\d{2}:\\d{2}:\\d{2}(?:\\.\\d{3})?)\\]\\s+(?P<action>.+?)\\s+(?P<subcomponent>.+?)\\s+(?P<details>.+)